title: "jekyll-new"
description: "Starting point with many features to build your very own awesome Jekyll theme."
author:
  name: "jekyll-new"
  email: "veller950@gmail.com"
  url: "https://vllur.github.io"

url: "https://vllur.github.io"
baseurl: /to-do-list

source: .
destination: ./_site

sass:
    style: compressed

exclude: [vendor]

owner: "vllur"
lang: "en_GB"
iso-lang: "en"
