title: "To-do List"
description: "To do list web application."

url: "https://vllur.github.io"
baseurl: /to-do-list

source: .
destination: ./_site

sass:
    style: compressed

exclude: [vendor]

owner: "vllur"
lang: "en_GB"
iso-lang: "en"
